import math

DEBUG = False
DEBUG_TILER = False

DEFAULT_MEMORY_LIMIT = 2048*(2**20)

CUDA_DEFAULT_THREAD_PER_BLOCK = 16
CUDA_DEFAULT_BLOCK_DIM = (math.floor(math.sqrt(CUDA_DEFAULT_THREAD_PER_BLOCK)), math.floor(math.sqrt(CUDA_DEFAULT_THREAD_PER_BLOCK)))